"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# For custom settings, see from line 128.

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u=l6*wxktvp&5zg_@!91b#(a@crv34ae&f$p50@7or1l84@zm='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -------------------------------------------------------------------------------------------------
# Above are default, below were added:
# -------------------------------------------------------------------------------------------------

ALLOWED_HOSTS += ["localhost", "host.docker.internal", "<YOUR_IP>"]

LOGIN_URL = '/login/'

INSTALLED_APPS += [
    # django-oidc-provider
    'oidc_provider',
]

# Docs: https://django-oidc-provider.readthedocs.io/en/master/sections/sessionmanagement.html#sessionmanagement
# MIDDLEWARE += ['oidc_provider.middleware.SessionManagementMiddleware',]

# https://django-oidc-provider.readthedocs.io/en/master/sections/scopesclaims.html#scopes-and-claims

# Spiff needs 'name' or 'preferred_username', doesn't failover with 'sub', without CLAIMS the UI shows only ';'
OIDC_IDTOKEN_INCLUDE_CLAIMS = True

# By default django-oidc-provider returns only 'nickname' with CLAIMS, but
# Spiff needs 'name' or 'preferred_username' (NavigationBar.tsx:115)
# This setting specifies a custom function for adjusting userinfo.
OIDC_USERINFO = "polls.oidc_provider_settings.userinfo"

# Custom function for adjusting what is returned in 'sub' (returns username.id by default)
OIDC_IDTOKEN_SUB_GENERATOR = "polls.oidc_provider_settings.sub_generator"

# Custom class for adding non-standard scope claims. Not needed for minimal example.
# Note that the class needs to explicitly return standard claims using functions.
# OIDC_EXTRA_SCOPE_CLAIMS = "polls.oidc_provider_settings.CustomScopeClaims"

# OIDC_SESSION_MANAGEMENT_ENABLE = True

TEMPLATES[0]['DIRS'] = [Path(BASE_DIR, "polls", "templates")]